# Generated by Django 5.1.1 on 2024-10-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('ticket_type', models.CharField(choices=[('VIP', 'VIP'), ('WITH_SPACE', 'With Space'), ('WITHOUT_SPACE', 'Without Space'), ('GROUP', 'Group')], default='VIP', max_length=13)),
            ],
        ),
    ]
